// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using album_collection;

namespace album_collection.Migrations
{
    [DbContext(typeof(ACDbContext))]
    [Migration("20210722154116_seed_data_init")]
    partial class seed_data_init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Image = "",
                            Name = "Back in Black"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            Image = "",
                            Name = "Highway to Hell"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            Image = "",
                            Name = "No Code"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 2,
                            Image = "",
                            Name = "Riot Act"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 3,
                            Image = "",
                            Name = "It's Only Rock 'n Roll"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hometown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordLabel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 48,
                            Biography = "AC/DC are an Australian rock band formed in Sydney in 1973 by Scottish-born brothers Malcolm and Angus Young. Their music has been variously described as hard rock, blues rock, and heavy metal, but the band themselves call it simply \"rock and roll\".",
                            Hometown = "Sydney, Australia",
                            Image = "",
                            Name = "ACDC",
                            RecordLabel = "Columbia"
                        },
                        new
                        {
                            Id = 2,
                            Age = 31,
                            Biography = "Pearl Jam is an American rock band formed in Seattle, Washington, in 1990. The band's line up consists of founding members Jeff Ament, Stone Gossard, Mike McCready, and Eddie Vedder, as well as Matt Cameron, who joined in 1998. Keyboardist Boom Gaspar has also been a touring/session member with the band since 2002.",
                            Hometown = "Seattle, Washington",
                            Image = "",
                            Name = "Pearl Jam",
                            RecordLabel = "Monkeywrench"
                        },
                        new
                        {
                            Id = 3,
                            Age = 59,
                            Biography = "The Rolling Stones are an English rock band formed in London in 1962. Diverging from the pop rock of the early-1960s, the Rolling Stones pioneered the gritty, heavier-driven sound that came to define hard rock.",
                            Hometown = "London, United Kingdom",
                            Image = "",
                            Name = "Rolling Stones",
                            RecordLabel = "Polydor"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Content = "Greetings young or old fellow. This here album is top tier. I would highly recommend satisfying your ear holes with these fine tunes.",
                            EditDate = new DateTime(2021, 7, 22, 11, 41, 14, 828, DateTimeKind.Local).AddTicks(6311),
                            PostDate = new DateTime(2021, 7, 22, 11, 41, 14, 814, DateTimeKind.Local).AddTicks(1410),
                            Rating = 4,
                            UserName = "AngusLover73"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 3,
                            Content = "OMG I LOVEZ DIS ALEBUMY! XD",
                            EditDate = new DateTime(2021, 7, 22, 11, 41, 14, 828, DateTimeKind.Local).AddTicks(9852),
                            PostDate = new DateTime(2021, 7, 22, 11, 41, 14, 828, DateTimeKind.Local).AddTicks(9824),
                            Rating = 5,
                            UserName = "PearlIsMyJam"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int?>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Duration = 310,
                            Link = "",
                            Name = "Hells Bells"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            Duration = 317,
                            Link = "",
                            Name = "Shoot to Thrill"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 1,
                            Duration = 213,
                            Link = "",
                            Name = "What Do You Do for Money Honey"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 1,
                            Duration = 210,
                            Link = "",
                            Name = "Given the Dog a Bone"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 1,
                            Duration = 256,
                            Link = "",
                            Name = "Let Me Put My Love into You"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 1,
                            Duration = 255,
                            Link = "",
                            Name = "Back in Black"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 1,
                            Duration = 210,
                            Link = "",
                            Name = "You Shook Me All Night Long"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 1,
                            Duration = 237,
                            Link = "",
                            Name = "Have a Drink on Me"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 1,
                            Duration = 246,
                            Link = "",
                            Name = "Shake a Leg"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 1,
                            Duration = 255,
                            Link = "",
                            Name = "Rock and Roll Ain't Noise Pollution"
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 2,
                            Duration = 209,
                            Link = "",
                            Name = "Highway to Hell"
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 2,
                            Duration = 204,
                            Link = "",
                            Name = "Girls Got Rhythm"
                        },
                        new
                        {
                            Id = 13,
                            AlbumId = 2,
                            Duration = 310,
                            Link = "",
                            Name = "Walk Over You"
                        },
                        new
                        {
                            Id = 14,
                            AlbumId = 2,
                            Duration = 268,
                            Link = "",
                            Name = "Touch Too Much"
                        },
                        new
                        {
                            Id = 15,
                            AlbumId = 2,
                            Duration = 235,
                            Link = "",
                            Name = "Beating Around the Bush"
                        },
                        new
                        {
                            Id = 16,
                            AlbumId = 2,
                            Duration = 203,
                            Link = "",
                            Name = "Shot Down in Flames"
                        },
                        new
                        {
                            Id = 17,
                            AlbumId = 2,
                            Duration = 155,
                            Link = "",
                            Name = "Get It Hot"
                        },
                        new
                        {
                            Id = 18,
                            AlbumId = 2,
                            Duration = 278,
                            Link = "",
                            Name = "If You Want Blood (You've Got It)"
                        },
                        new
                        {
                            Id = 19,
                            AlbumId = 2,
                            Duration = 258,
                            Link = "",
                            Name = "Love Hungry Man"
                        },
                        new
                        {
                            Id = 20,
                            AlbumId = 2,
                            Duration = 378,
                            Link = "",
                            Name = "Night Prowler"
                        },
                        new
                        {
                            Id = 21,
                            AlbumId = 3,
                            Duration = 160,
                            Link = "",
                            Name = "Sometimes"
                        },
                        new
                        {
                            Id = 22,
                            AlbumId = 3,
                            Duration = 221,
                            Link = "",
                            Name = "Hail, Hail"
                        },
                        new
                        {
                            Id = 23,
                            AlbumId = 3,
                            Duration = 230,
                            Link = "",
                            Name = "Who You Are"
                        },
                        new
                        {
                            Id = 24,
                            AlbumId = 3,
                            Duration = 239,
                            Link = "",
                            Name = "In My Tree"
                        },
                        new
                        {
                            Id = 25,
                            AlbumId = 3,
                            Duration = 232,
                            Link = "",
                            Name = "Smile"
                        },
                        new
                        {
                            Id = 26,
                            AlbumId = 3,
                            Duration = 362,
                            Link = "",
                            Name = "Off He Goes"
                        },
                        new
                        {
                            Id = 27,
                            AlbumId = 3,
                            Duration = 215,
                            Link = "",
                            Name = "Habit"
                        },
                        new
                        {
                            Id = 28,
                            AlbumId = 3,
                            Duration = 243,
                            Link = "",
                            Name = "Red Mosquito"
                        },
                        new
                        {
                            Id = 29,
                            AlbumId = 3,
                            Duration = 62,
                            Link = "",
                            Name = "Lukin'"
                        },
                        new
                        {
                            Id = 30,
                            AlbumId = 3,
                            Duration = 346,
                            Link = "",
                            Name = "Present Tense"
                        },
                        new
                        {
                            Id = 31,
                            AlbumId = 3,
                            Duration = 208,
                            Link = "",
                            Name = "Mankind"
                        },
                        new
                        {
                            Id = 32,
                            AlbumId = 3,
                            Duration = 177,
                            Link = "",
                            Name = "I'm Open"
                        },
                        new
                        {
                            Id = 33,
                            AlbumId = 3,
                            Duration = 275,
                            Link = "",
                            Name = "Around the Bend"
                        },
                        new
                        {
                            Id = 34,
                            AlbumId = 4,
                            Duration = 219,
                            Link = "",
                            Name = "Can't Keep"
                        },
                        new
                        {
                            Id = 35,
                            AlbumId = 4,
                            Duration = 230,
                            Link = "",
                            Name = "Save You"
                        },
                        new
                        {
                            Id = 36,
                            AlbumId = 4,
                            Duration = 276,
                            Link = "",
                            Name = "Love Boat Captain"
                        },
                        new
                        {
                            Id = 37,
                            AlbumId = 4,
                            Duration = 231,
                            Link = "",
                            Name = "Cropduster"
                        },
                        new
                        {
                            Id = 38,
                            AlbumId = 4,
                            Duration = 195,
                            Link = "",
                            Name = "Ghost"
                        },
                        new
                        {
                            Id = 39,
                            AlbumId = 4,
                            Duration = 215,
                            Link = "",
                            Name = "I Am Mine"
                        },
                        new
                        {
                            Id = 40,
                            AlbumId = 4,
                            Duration = 250,
                            Link = "",
                            Name = "Thumbing My Way"
                        },
                        new
                        {
                            Id = 41,
                            AlbumId = 4,
                            Duration = 270,
                            Link = "",
                            Name = "You Are"
                        },
                        new
                        {
                            Id = 42,
                            AlbumId = 4,
                            Duration = 158,
                            Link = "",
                            Name = "Get Right"
                        },
                        new
                        {
                            Id = 43,
                            AlbumId = 4,
                            Duration = 161,
                            Link = "",
                            Name = "Green Disease"
                        },
                        new
                        {
                            Id = 44,
                            AlbumId = 4,
                            Duration = 215,
                            Link = "",
                            Name = "Help Help"
                        },
                        new
                        {
                            Id = 45,
                            AlbumId = 4,
                            Duration = 237,
                            Link = "",
                            Name = "Bu$hleaguer"
                        },
                        new
                        {
                            Id = 46,
                            AlbumId = 4,
                            Duration = 250,
                            Link = "",
                            Name = "1/2 Full"
                        },
                        new
                        {
                            Id = 47,
                            AlbumId = 4,
                            Duration = 65,
                            Link = "",
                            Name = "Arc"
                        },
                        new
                        {
                            Id = 48,
                            AlbumId = 4,
                            Duration = 277,
                            Link = "",
                            Name = "All or None"
                        },
                        new
                        {
                            Id = 49,
                            AlbumId = 5,
                            Duration = 226,
                            Link = "",
                            Name = "If You Can't Rock Me"
                        },
                        new
                        {
                            Id = 50,
                            AlbumId = 5,
                            Duration = 210,
                            Link = "",
                            Name = "Ain't Too Proud to Beg"
                        },
                        new
                        {
                            Id = 51,
                            AlbumId = 5,
                            Duration = 307,
                            Link = "",
                            Name = "It's Only Rock 'n Roll (But I Like It)"
                        },
                        new
                        {
                            Id = 52,
                            AlbumId = 5,
                            Duration = 277,
                            Link = "",
                            Name = "Till the Next Goodbye"
                        },
                        new
                        {
                            Id = 53,
                            AlbumId = 5,
                            Duration = 397,
                            Link = "",
                            Name = "Time Waits for No One"
                        },
                        new
                        {
                            Id = 54,
                            AlbumId = 5,
                            Duration = 300,
                            Link = "",
                            Name = "Luxury"
                        },
                        new
                        {
                            Id = 55,
                            AlbumId = 5,
                            Duration = 251,
                            Link = "",
                            Name = "Dance Little Sister"
                        },
                        new
                        {
                            Id = 56,
                            AlbumId = 5,
                            Duration = 376,
                            Link = "",
                            Name = "If You Really Want to Be My Friend"
                        },
                        new
                        {
                            Id = 57,
                            AlbumId = 5,
                            Duration = 163,
                            Link = "",
                            Name = "Short and Curlies"
                        },
                        new
                        {
                            Id = 58,
                            AlbumId = 5,
                            Duration = 393,
                            Link = "",
                            Name = "Fingerprint File"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.HasOne("album_collection.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("album_collection.Models.Review", b =>
                {
                    b.HasOne("album_collection.Models.Album", "Album")
                        .WithMany("Reviews")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("album_collection.Models.Song", b =>
                {
                    b.HasOne("album_collection.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("album_collection.Models.Artist", null)
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("album_collection.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
